name: white_fullscreen
description: "Flutter app for Android to show a blank screen."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wakelock_plus: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
